export const SET_GOODS_DETAIL = 'SET_GOODS_DETAIL'

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

export const SET_SHOP_CAR_FULL_SCREEN = 'SET_SHOP_CAR_FULL_SCREEN'

export const SET_CAR_COUNT = 'SET_CAR_COUNT'

export const SET_CAR_LIST = 'SET_CAR_LIST'
